---
services:
  mattermost:
    image: mattermost/mattermost-team-edition
    container_name: mattermost
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_SQLSETTINGS_DATASOURCE=postgres://bohan_thuillier:bohan_thuillier@35.239.186.51/bohan_thuillier?sslmode=disable&connect_timeout=10
    ports:
      - 8065:8065